# Makefile for building program
# Generated by tmake at 16:13, 2016/12/08
#     Project: program.pro
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-g -pipe -Wall -W -O3 -finline-functions -finline-limit=38400 -fno-strict-aliasing -Winline 
CXXFLAGS=	-g -pipe -Wall -W -O3 -finline-functions -finline-limit=38400 -fno-strict-aliasing -Winline 
INCPATH	=	
LINK	=	g++
LFLAGS	=	
LIBS	=	$(SUBLIBS)  
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic
REMOVE	=	rm -f
TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	A.hpp
SOURCES =	A.cpp \
		main.cpp
OBJECTS =	A.o \
		main.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	program
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(REMOVE) $(TARGET) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake:
	tmake program.pro

dist:
	$(REMOVE) Makefile *.kdevprj *.kdevses core* *~

clean:
	$(REMOVE) $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)


####### Compile

A.o: A.cpp

main.o: main.cpp

